{
  "debug": true,
  "server": {
    "address": ":9090",
    "timeout": "30",
  },
  "context": {
    "timeout": 2
  },
  "database": {
    "host": "localhost",
    "port": "26257",
    "user": "aula",
    "password": "aula@321",
    "name": "aula"
  }

}
